[package]
name = "mesh_tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
nalgebra = "0.32.3"
rand = "0.8.5"
clap = "4.0.32"
